import { Project } from './Project';

export const PROJECTS = [
    new Project({
        id: 1,
        name: 'Logan Holmes Runs',
        description: 'Website and mobile app to visualize my running data. Built in Wordpress (PHP backend) using a theme created from scratch. Interfaces with the Strava API. Uses multiple visualization techniques with Leafet and OpenMapBox.',
        reason: 'personal',
        images: ['lhr_map.png', 'lhr_app.png'],
        siteUrl: 'https://www.loganholmesruns.com',
        iosUrl: 'https://apps.apple.com/in/app/logan-holmes-runs/id6447003853',
        ranking: 1,
    }),
    new Project({
        id: 2,
        name: 'Gym Vision',
        description: '',
        reason: 'personal',
        ranking: 2,
    }),
    new Project({
        id: 3,
        name: 'Race Livetracking',
        description: '',
        reason: 'personal',
        githubUrl: '',
        ranking: 3,
    }),
    new Project({
        id: 4,
        name: 'Grid Wars Game',
        description: '',
        reason: 'personal',
        siteUrl: '',
        ranking: 4,
    }),
    new Project({
        id: 5,
        name: 'Tank Wars',
        description: '',
        reason: 'school',
        ranking: 1,
    }),
    new Project({
        id: 6,
        name: 'TA Website',
        description: '',
        reason: 'school',
        ranking: 2,
    }),
    new Project({
        id: 7,
        name: 'Sprite Animator',
        description: '',
        reason: 'school',
        ranking: 3,
    }),
    new Project({
        id: 8,
        name: 'Football Play Creator',
        description: '',
        reason: 'school',
        ranking: 4,
    }),
    new Project({
        id: 9,
        name: 'Statistics Dashboard',
        description: '',
        reason: 'work',
        ranking: 1,
    }),
    new Project({
        id: 10,
        name: 'In Store Displays',
        description: '',
        reason: 'work',
        ranking: 3,
    }),
    new Project({
        id: 11,
        name: 'Data Visualization Website',
        description: '',
        reason: 'work',
        ranking: 2,
    }),
];