import { Course } from './Course';

export const COURSES = [
    new Course({
        id: 1,
        name: 'Databases',
        description: 'Understanding of database planning, creation, and use. Learned to make ER diagrams. Designed and implemented a database system for a LMS (Learning Management System).',
        technologies: ['MySQL'],
        images: ['no_image.jpg'],
        grade: 95,
        ranking: 4,
    }),
    new Course({
        id: 2,
        name: 'Mobile App Programming',
        description: 'Devleopment of android mobile app using Kotlin. Created a lifestyle app. Worked with gathering and storing user information on device. Used intents to interact with the built in camera and maps application. Interfaced with API to gather weather information.',
        technologies: ['Kotlin'],
        images: ['la_horiz.png', 'la_profile.png'],
        grade: 100,
        ranking: 5,
    }),
    new Course({
        id: 3,
        name: 'Web Software Architecture',
        description: 'Full stack development of web application in ASP.NET Core. Use of code first database techniques. Hosted on AWS.',
        technologies: ['C#', 'JS', 'AWS'],
        images: ['no_image.jpg'],
        grade: 98,
        ranking: 3,
    }),
    new Course({
        id: 4,
        name: 'Deep Learning',
        description: 'Introduction to types of deep learning models. Topics included loss functions, optimization, regularization, class visualization, saliency maps, fooling images. Built GAN to generate images of drawn numbers trained on MNIST dataset, RNN for image captioning, and CNN for classification on CIFAR-10 dataset.',
        technologies: ['Python', 'Numpy'],
        images: ['DL_1.png', 'DL_2.png', 'DL_3.png', 'DL_4.png', 'DL_5.png'],
        grade: 95,
        ranking: 1,
    }),
    new Course({
        id: 5,
        name: 'Computer Vision',
        description: 'Used OpenCV to perform many data transformations on images using common advanced computer vision techniques to achieve desired results. Techniques included edge detection using hough lines, feature detection, image alignment and stitching, stereo matching, and motion detection.',
        images: ['CV_1.png', 'CV_2.png', 'CV_3.png'],
        technologies: ['Python', 'OpenCV', 'TensorFlow'],
        grade: 95,
        ranking: 2,
    }),
    new Course({
        id: 6,
        name: 'Capstone',
        description: 'GymVision: Senior capstone project to give better data to gym owners. Uses computer vision (OpenCv in python) on an embedded device (rapsberry pi) to detect visible persons and gym equipment to give data insights based on collected information. Insights include: equipment usage statistics, crowd levels, heat maps, predicted crowd levels. Website and database hosted on Azure. Azure function is called by the pi to update the database.',
        technologies: ['Python', 'OpenCV', 'SQL', 'C#', 'Azure', 'JS'],
        images: ['gv_site.png', 'gv_mockup.png'],
        grade: 95,
        ranking: 6,
    }),
    new Course({
        id: 7,
        name: 'Software Practice II',
        description: 'Built python app using QT Creator allowing users to create football plays. The plays are stored and there is an option to study and test on the plays created. Playbooks can be saved and loaded to the file system.',
        technologies: ['Python', 'QT Creator'],
        images: ['pb_home.png', 'pb_create.png', 'pb_study.png', 'pb_test.png'],
        grade: 95,
        ranking: 7,
    }),
    new Course({
        id: 8,
        name: 'Software Practice I',
        description: 'Created an online multiplayer tank shooting game with a custom programmed server and client system. Uses websockets to establish connections and send data between client and server.',
        technologies: ['Windows Forms App', 'Web Sockets'],
        images: ['tanks_playing.png'],
        grade: 95,
        ranking: 8,
    }),
];